package de.u808.simpleinquest.domain;
// Generated 24.10.2009 14:00:41 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QrtzLocks generated by hbm2java
 */
@Entity
@Table(name = "QRTZ_LOCKS", schema = "PUBLIC")
public class QrtzLocks implements java.io.Serializable {

	private String lockName;

	public QrtzLocks() {
	}

	public QrtzLocks(String lockName) {
		this.lockName = lockName;
	}

	@Id
	@Column(name = "LOCK_NAME", unique = true, nullable = false, length = 40)
	public String getLockName() {
		return this.lockName;
	}

	public void setLockName(String lockName) {
		this.lockName = lockName;
	}

}
