package de.u808.simpleinquest.domain;
// Generated 24.10.2009 14:00:41 by Hibernate Tools 3.2.5.Beta

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QrtzJobListeners generated by hbm2java
 */
@Entity
@Table(name = "QRTZ_JOB_LISTENERS", schema = "PUBLIC")
public class QrtzJobListeners implements java.io.Serializable {

	private QrtzJobListenersId id;
	private QrtzJobDetails qrtzJobDetails;

	public QrtzJobListeners() {
	}

	public QrtzJobListeners(QrtzJobListenersId id, QrtzJobDetails qrtzJobDetails) {
		this.id = id;
		this.qrtzJobDetails = qrtzJobDetails;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "jobName", column = @Column(name = "JOB_NAME", nullable = false, length = 80)),
			@AttributeOverride(name = "jobGroup", column = @Column(name = "JOB_GROUP", nullable = false, length = 80)),
			@AttributeOverride(name = "jobListener", column = @Column(name = "JOB_LISTENER", nullable = false, length = 80)) })
	public QrtzJobListenersId getId() {
		return this.id;
	}

	public void setId(QrtzJobListenersId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "JOB_NAME", referencedColumnName = "JOB_NAME", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "JOB_GROUP", referencedColumnName = "JOB_GROUP", nullable = false, insertable = false, updatable = false) })
	public QrtzJobDetails getQrtzJobDetails() {
		return this.qrtzJobDetails;
	}

	public void setQrtzJobDetails(QrtzJobDetails qrtzJobDetails) {
		this.qrtzJobDetails = qrtzJobDetails;
	}

}
