package de.u808.simpleinquest.domain;
// Generated 24.10.2009 14:00:41 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QrtzJobDetails generated by hbm2java
 */
@Entity
@Table(name = "QRTZ_JOB_DETAILS", schema = "PUBLIC")
public class QrtzJobDetails implements java.io.Serializable {

	private QrtzJobDetailsId id;
	private String description;
	private String jobClassName;
	private String isDurable;
	private String isVolatile;
	private String isStateful;
	private String requestsRecovery;
	private byte[] jobData;
	private Set<QrtzJobListeners> qrtzJobListenerses = new HashSet<QrtzJobListeners>(
			0);
	private Set<QrtzTriggers> qrtzTriggerses = new HashSet<QrtzTriggers>(0);

	public QrtzJobDetails() {
	}

	public QrtzJobDetails(QrtzJobDetailsId id, String jobClassName,
			String isDurable, String isVolatile, String isStateful,
			String requestsRecovery) {
		this.id = id;
		this.jobClassName = jobClassName;
		this.isDurable = isDurable;
		this.isVolatile = isVolatile;
		this.isStateful = isStateful;
		this.requestsRecovery = requestsRecovery;
	}

	public QrtzJobDetails(QrtzJobDetailsId id, String description,
			String jobClassName, String isDurable, String isVolatile,
			String isStateful, String requestsRecovery, byte[] jobData,
			Set<QrtzJobListeners> qrtzJobListenerses,
			Set<QrtzTriggers> qrtzTriggerses) {
		this.id = id;
		this.description = description;
		this.jobClassName = jobClassName;
		this.isDurable = isDurable;
		this.isVolatile = isVolatile;
		this.isStateful = isStateful;
		this.requestsRecovery = requestsRecovery;
		this.jobData = jobData;
		this.qrtzJobListenerses = qrtzJobListenerses;
		this.qrtzTriggerses = qrtzTriggerses;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "jobName", column = @Column(name = "JOB_NAME", nullable = false, length = 80)),
			@AttributeOverride(name = "jobGroup", column = @Column(name = "JOB_GROUP", nullable = false, length = 80)) })
	public QrtzJobDetailsId getId() {
		return this.id;
	}

	public void setId(QrtzJobDetailsId id) {
		this.id = id;
	}

	@Column(name = "DESCRIPTION", length = 120)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "JOB_CLASS_NAME", nullable = false, length = 128)
	public String getJobClassName() {
		return this.jobClassName;
	}

	public void setJobClassName(String jobClassName) {
		this.jobClassName = jobClassName;
	}

	@Column(name = "IS_DURABLE", nullable = false, length = 1)
	public String getIsDurable() {
		return this.isDurable;
	}

	public void setIsDurable(String isDurable) {
		this.isDurable = isDurable;
	}

	@Column(name = "IS_VOLATILE", nullable = false, length = 1)
	public String getIsVolatile() {
		return this.isVolatile;
	}

	public void setIsVolatile(String isVolatile) {
		this.isVolatile = isVolatile;
	}

	@Column(name = "IS_STATEFUL", nullable = false, length = 1)
	public String getIsStateful() {
		return this.isStateful;
	}

	public void setIsStateful(String isStateful) {
		this.isStateful = isStateful;
	}

	@Column(name = "REQUESTS_RECOVERY", nullable = false, length = 1)
	public String getRequestsRecovery() {
		return this.requestsRecovery;
	}

	public void setRequestsRecovery(String requestsRecovery) {
		this.requestsRecovery = requestsRecovery;
	}

	@Column(name = "JOB_DATA")
	public byte[] getJobData() {
		return this.jobData;
	}

	public void setJobData(byte[] jobData) {
		this.jobData = jobData;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qrtzJobDetails")
	public Set<QrtzJobListeners> getQrtzJobListenerses() {
		return this.qrtzJobListenerses;
	}

	public void setQrtzJobListenerses(Set<QrtzJobListeners> qrtzJobListenerses) {
		this.qrtzJobListenerses = qrtzJobListenerses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qrtzJobDetails")
	public Set<QrtzTriggers> getQrtzTriggerses() {
		return this.qrtzTriggerses;
	}

	public void setQrtzTriggerses(Set<QrtzTriggers> qrtzTriggerses) {
		this.qrtzTriggerses = qrtzTriggerses;
	}

}
