package de.u808.simpleinquest.domain;
// Generated 24.10.2009 14:00:41 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QrtzPausedTriggerGrps generated by hbm2java
 */
@Entity
@Table(name = "QRTZ_PAUSED_TRIGGER_GRPS", schema = "PUBLIC")
public class QrtzPausedTriggerGrps implements java.io.Serializable {

	private String triggerGroup;

	public QrtzPausedTriggerGrps() {
	}

	public QrtzPausedTriggerGrps(String triggerGroup) {
		this.triggerGroup = triggerGroup;
	}

	@Id
	@Column(name = "TRIGGER_GROUP", unique = true, nullable = false, length = 80)
	public String getTriggerGroup() {
		return this.triggerGroup;
	}

	public void setTriggerGroup(String triggerGroup) {
		this.triggerGroup = triggerGroup;
	}

}
